server.port=${PORT:8443}
logging.level.org.atmosphere=warn
server.address=0.0.0.0

# Launch the default browser when starting the application in development mode
vaadin.launch-browser=true
spring.main.allow-bean-definition-overriding=true

# To improve the performance during development.
# For more information https://vaadin.com/docs/latest/flow/integrations/spring/configuration#special-configuration-parameters
vaadin.allowed-packages=com.vaadin,org.vaadin,com.flowingcode,com.riquitos

server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=riquitos
server.ssl.key-alias=riquitos
server.ssl.enabled=true

#DATABASE CONFIG
spring.datasource.url=jdbc:postgresql://localhost:5432/riquitoserp
spring.datasource.username=postgres
spring.datasource.password=niidea2004
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

spring.datasource.hikari.pool-name=FullCars-HikariPool
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

#BACKUP CONFIG
app.backup.directory=./backups
app.backup.max-backups=15
app.backup.auto-enabled=true
spring.datasource.pgrestore-path=C:/Program Files/PostgreSQL/16/bin/pg_restore.exe
spring.datasource.pgdump-path=C:\\Program Files\\PostgreSQL\\16\\bin\\pg_dump.exe

spring.jpa.show-sql=true              
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.batch_size=500
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
