export interface VehicleData {
  id: string;
  name: string;
  brand: string;
  model: string;
  image: string;
  price: string;
  priceNumber: number;
  type: "venta" | "alquiler";
  year: number;
  kilometers: string;
  kilometersNumber: number;
  location: string;
  fuel: string;
  transmission: string;
  engine: string;
  color: string;
  doors: number;
  passengers: number;
  insurance?: string;
  franchise?: string;
  features: string[];
  description: string;
}

export const allVehicles: VehicleData[] = [
  // Venta
  {
    id: "toyota-corolla-2023",
    name: "Toyota Corolla XEi",
    brand: "Toyota",
    model: "Corolla",
    image: "https://images.unsplash.com/photo-1623869675781-80aa31012a5a?q=80&w=2670&auto=format&fit=crop",
    price: "18.500.000",
    priceNumber: 18500000,
    type: "venta",
    year: 2023,
    kilometers: "15.000 km",
    kilometersNumber: 15000,
    location: "Alsina",
    fuel: "Nafta",
    transmission: "Automática CVT",
    engine: "2.0L 170cv",
    color: "Blanco Perlado",
    doors: 4,
    passengers: 5,
    features: ["Control crucero adaptativo", "Cámara trasera", "Android Auto/Apple CarPlay", "Sensores de estacionamiento", "Climatizador bizona", "Llantas de aleación 17\""],
    description: "Toyota Corolla XEi en excelente estado, único dueño, service oficial al día. Interior impecable, nunca fumado. Ideal para quien busca confort, seguridad y bajo consumo."
  },
  {
    id: "vw-vento-2022",
    name: "Volkswagen Vento GLI",
    brand: "Volkswagen",
    model: "Vento",
    image: "https://images.unsplash.com/photo-1631295387526-d81b7cc4a775?q=80&w=2574&auto=format&fit=crop",
    price: "22.000.000",
    priceNumber: 22000000,
    type: "venta",
    year: 2022,
    kilometers: "28.000 km",
    kilometersNumber: 28000,
    location: "Alsina",
    fuel: "Nafta",
    transmission: "Automática DSG",
    engine: "2.0 TSI 230cv",
    color: "Gris Platino",
    doors: 4,
    passengers: 5,
    features: ["Techo solar", "Asientos deportivos", "Faros LED Matrix", "Frenos deportivos", "Escape deportivo", "Modo Sport"],
    description: "El Vento más deportivo de la gama. Potencia y confort en un solo auto. Mantenimiento al día en concesionario oficial. Equipamiento full."
  },
  {
    id: "ford-ranger-2023",
    name: "Ford Ranger Limited",
    brand: "Ford",
    model: "Ranger",
    image: "https://images.unsplash.com/photo-1551830820-330a71b99659?q=80&w=2670&auto=format&fit=crop",
    price: "35.000.000",
    priceNumber: 35000000,
    type: "venta",
    year: 2023,
    kilometers: "12.000 km",
    kilometersNumber: 12000,
    location: "DelRio",
    fuel: "Diesel",
    transmission: "Automática 10 velocidades",
    engine: "3.0L V6 250cv",
    color: "Azul Lightning",
    doors: 4,
    passengers: 5,
    features: ["Caja automática 10 velocidades", "Tracción 4x4", "SYNC 4", "Cámara 360°", "Control de descenso", "Asientos de cuero"],
    description: "Nueva generación de Ranger. Motor V6 TDCi de gran potencia. Ideal para trabajo y aventura. Garantía de fábrica vigente."
  },
  {
    id: "peugeot-208-2023",
    name: "Peugeot 208 Allure",
    brand: "Peugeot",
    model: "208",
    image: "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?q=80&w=2670&auto=format&fit=crop",
    price: "14.500.000",
    priceNumber: 14500000,
    type: "venta",
    year: 2023,
    kilometers: "8.000 km",
    kilometersNumber: 8000,
    location: "Alsina 2",
    fuel: "Nafta",
    transmission: "Manual 6 velocidades",
    engine: "1.6L 115cv",
    color: "Rojo Elixir",
    doors: 5,
    passengers: 5,
    features: ["i-Cockpit 3D", "Pantalla 10\"", "LED Vision", "Mirror Screen", "Alerta de colisión", "Detector de fatiga"],
    description: "El 208 más tecnológico. Diseño europeo, bajo consumo y equipamiento premium. Perfecto para la ciudad."
  },
  {
    id: "chevrolet-cruze-2022",
    name: "Chevrolet Cruze LTZ",
    brand: "Chevrolet",
    model: "Cruze",
    image: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?q=80&w=2670&auto=format&fit=crop",
    price: "19.800.000",
    priceNumber: 19800000,
    type: "venta",
    year: 2022,
    kilometers: "32.000 km",
    kilometersNumber: 32000,
    location: "Alsina",
    fuel: "Nafta",
    transmission: "Automática 6 velocidades",
    engine: "1.4 Turbo 153cv",
    color: "Negro",
    doors: 4,
    passengers: 5,
    features: ["MyLink 8\"", "OnStar", "Tapizado de cuero", "Techo solar", "Sensores delanteros y traseros", "Control de tracción"],
    description: "Cruze LTZ full, el más equipado. Excelente relación precio-equipamiento. Service al día."
  },
  {
    id: "fiat-cronos-2024",
    name: "Fiat Cronos Precision",
    brand: "Fiat",
    model: "Cronos",
    image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?q=80&w=2670&auto=format&fit=crop",
    price: "16.200.000",
    priceNumber: 16200000,
    type: "venta",
    year: 2024,
    kilometers: "0 km",
    kilometersNumber: 0,
    location: "DelRio",
    fuel: "Nafta",
    transmission: "Automática CVT",
    engine: "1.8L 130cv",
    color: "Blanco Alaska",
    doors: 4,
    passengers: 5,
    features: ["Pantalla 10.1\"", "Wireless CarPlay", "Start/Stop", "6 Airbags", "Control de estabilidad", "Cámara de retroceso"],
    description: "0KM con entrega inmediata. Versión tope de gama con todos los accesorios. Financiación disponible."
  },
  // Alquiler
  {
    id: "chevrolet-onix-alquiler",
    name: "Chevrolet Onix LT",
    brand: "Chevrolet",
    model: "Onix",
    image: "https://images.unsplash.com/photo-1609521263047-f8f205293f24?q=80&w=2580&auto=format&fit=crop",
    price: "65.000",
    priceNumber: 65000,
    type: "alquiler",
    year: 2022,
    kilometers: "18.000 km",
    kilometersNumber: 18000,
    location: "DelRio",
    fuel: "Nafta",
    transmission: "Manual 5 velocidades",
    engine: "1.0 Turbo 116cv",
    color: "Gris Satin Steel",
    doors: 5,
    passengers: 5,
    insurance: "Todo riesgo",
    franchise: "18%",
    features: ["Aire acondicionado", "Dirección asistida", "Cierre centralizado", "Bluetooth", "Radio con USB", "4 Airbags"],
    description: "Ideal para moverse por la ciudad. Bajo consumo y fácil de estacionar. Disponible para alquiler diario, semanal o mensual."
  },
  {
    id: "toyota-hilux-alquiler",
    name: "Toyota Hilux SRX",
    brand: "Toyota",
    model: "Hilux",
    image: "https://images.unsplash.com/photo-1612544448445-b8232cff3b6c?q=80&w=2574&auto=format&fit=crop",
    price: "120.000",
    priceNumber: 120000,
    type: "alquiler",
    year: 2023,
    kilometers: "25.000 km",
    kilometersNumber: 25000,
    location: "Alsina",
    fuel: "Diesel",
    transmission: "Automática 6 velocidades",
    engine: "2.8L 204cv",
    color: "Blanco",
    doors: 4,
    passengers: 5,
    insurance: "Todo riesgo",
    franchise: "25%",
    features: ["Tracción 4x4", "Control de tracción", "Diferencial trasero blocante", "Cámara trasera", "Climatizador", "Butacas de cuero"],
    description: "La pick-up más confiable del mercado. Perfecta para trabajo pesado o escapadas off-road. Capacidad de carga 1 tonelada."
  },
  {
    id: "renault-sandero-alquiler",
    name: "Renault Sandero Stepway",
    brand: "Renault",
    model: "Sandero",
    image: "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?q=80&w=2574&auto=format&fit=crop",
    price: "55.000",
    priceNumber: 55000,
    type: "alquiler",
    year: 2023,
    kilometers: "12.000 km",
    kilometersNumber: 12000,
    location: "DelRio",
    fuel: "Nafta",
    transmission: "Manual 5 velocidades",
    engine: "1.6L 118cv",
    color: "Naranja",
    doors: 5,
    passengers: 5,
    insurance: "Terceros completo",
    franchise: "15%",
    features: ["Media Nav", "Barras de techo", "Protectores laterales", "Cámara trasera", "Sensor de lluvia", "Aire acondicionado"],
    description: "Versión aventurera del Sandero. Mayor altura al piso y look robusto. Económico y versátil."
  },
  {
    id: "volkswagen-taos-alquiler",
    name: "Volkswagen Taos Highline",
    brand: "Volkswagen",
    model: "Taos",
    image: "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?q=80&w=2670&auto=format&fit=crop",
    price: "95.000",
    priceNumber: 95000,
    type: "alquiler",
    year: 2023,
    kilometers: "15.000 km",
    kilometersNumber: 15000,
    location: "Alsina",
    fuel: "Nafta",
    transmission: "Automática DSG",
    engine: "1.4 TSI 150cv",
    color: "Azul Reef",
    doors: 5,
    passengers: 5,
    insurance: "Todo riesgo",
    franchise: "20%",
    features: ["Digital Cockpit", "Techo panorámico", "Asientos calefaccionados", "Keyless entry", "IQ.Drive", "App Connect"],
    description: "SUV premium para viajes largos o uso ejecutivo. Confort superior y tecnología de punta."
  },
  {
    id: "fiat-mobi-alquiler",
    name: "Fiat Mobi Easy",
    brand: "Fiat",
    model: "Mobi",
    image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?q=80&w=2670&auto=format&fit=crop",
    price: "45.000",
    priceNumber: 45000,
    type: "alquiler",
    year: 2023,
    kilometers: "8.000 km",
    kilometersNumber: 8000,
    location: "Alsina 2",
    fuel: "Nafta",
    transmission: "Manual 5 velocidades",
    engine: "1.0L 75cv",
    color: "Rojo",
    doors: 5,
    passengers: 4,
    insurance: "Terceros completo",
    franchise: "12%",
    features: ["Aire acondicionado", "Dirección asistida", "Radio Bluetooth", "Cierre centralizado", "Vidrios eléctricos", "2 Airbags"],
    description: "El más económico de nuestra flota. Perfecto para uso urbano, fácil de maniobrar y estacionar."
  },
  {
    id: "peugeot-partner-alquiler",
    name: "Peugeot Partner Furgón",
    brand: "Peugeot",
    model: "Partner",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?q=80&w=2532&auto=format&fit=crop",
    price: "75.000",
    priceNumber: 75000,
    type: "alquiler",
    year: 2022,
    kilometers: "35.000 km",
    kilometersNumber: 35000,
    location: "DelRio",
    fuel: "Diesel",
    transmission: "Manual 5 velocidades",
    engine: "1.6 HDi 90cv",
    color: "Blanco",
    doors: 4,
    passengers: 2,
    insurance: "Todo riesgo",
    franchise: "20%",
    features: ["Capacidad 3.3m³", "Carga útil 650kg", "Puerta lateral deslizante", "Bluetooth", "Aire acondicionado", "Control de velocidad"],
    description: "Utilitario ideal para mudanzas, fletes o emprendimientos. Gran capacidad de carga y bajo consumo."
  },
];

export const brands = [...new Set(allVehicles.map(v => v.brand))].sort();
export const locations = [...new Set(allVehicles.map(v => v.location))].sort();
export const years = [...new Set(allVehicles.map(v => v.year))].sort((a, b) => b - a);
export const fuelTypes = [...new Set(allVehicles.map(v => v.fuel))].sort();
export const transmissions = [...new Set(allVehicles.map(v => v.transmission))].sort();
